### ISSUE TITLE
Executable called tsd2cee instead of tsd2cce and some errors under Windows

### ISSUE THREAD

**Issue by nano-rbu** [eredo/tsd2cce#4]
Hi, 
I am curious for your tool in order to generate three.js externs.

There seems to be a typo in the installation routine as the command will be called tsd2cee instead of tsd2cce after installation.

But even with this in mind, I wasn´t able to run the tool. 
I am getting this error:

```
C:\Users\xxxx\AppData\Roaming\npm\node_modules\tsd2cce\index.js:3
const Parser = require('./src/parser').Parser;
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\rbu\AppData\Roaming\npm\node_modules\tsd2cce\bin\tsd2cee:2:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

and if I remove `"use strict";` I get

```
C:\Users\xxxx\AppData\Roaming\npm\node_modules\tsd2cce\index.js:6
let argv = require('optimist')
    ^^^^
SyntaxError: Unexpected identifier
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\rbu\AppData\Roaming\npm\node_modules\tsd2cce\bin\tsd2cee:2:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

I apologize if this is a user error.

**Comment by eredo** [comment]
The tsd2cee is indeed an error. A fix will be done soon.

Regarding the other issue. Which version of node are you using? The program relies on node 5.X.
Thanks for the issue!

**Comment by nano-rbu** [comment]
Indeed: updating node to version 5 solved the problems.

Many thanks!
