### ISSUE TITLE
TypeError at parser.js:277

### ISSUE THREAD

**Issue by kchodorow** [eredo/tsd2cce#6]
I'm trying to run this on (three.d.ts)[https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/threejs/three.d.ts] and getting:

```
$ /usr/local/lib/node_modules/tsd2cce/bin/tsd2cee three.d.ts x.js
/usr/local/lib/node_modules/tsd2cce/src/parser.js:277
        type[member.name.text] = {};
                        ^

TypeError: Cannot read property 'text' of undefined
    at /usr/local/lib/node_modules/tsd2cce/src/parser.js:277:25
    at Array.forEach (native)
    at Parser.transformType_ (/usr/local/lib/node_modules/tsd2cce/src/parser.js:276:25)
    at Parser.appendType_ (/usr/local/lib/node_modules/tsd2cce/src/parser.js:238:23)
    at /usr/local/lib/node_modules/tsd2cce/src/parser.js:299:19
    at Array.map (native)
    at Parser.getParameters_ (/usr/local/lib/node_modules/tsd2cce/src/parser.js:298:28)
    at Parser.defineMethod (/usr/local/lib/node_modules/tsd2cce/src/parser.js:368:12)
    at traverse (/usr/local/lib/node_modules/tsd2cce/src/parser.js:79:16)
    at visitEachNode (/usr/local/lib/node_modules/tsd2cce/node_modules/typescript/lib/typescript.js:7255:30)
```

I installed from NPM:

```
$ npm list -g tsd2cce 
/usr/local/lib
└── tsd2cce@0.1.1 
```

Let me know if you need any other info!

**Comment by unphased** [comment]
This code works on an earlier version of three.d.ts, I picked the one that I tried that worked based on the note by @Corkle in three.js#341 (made on February 29 2016): 

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/c6c3d3e65dd2d7035428f9c7b371ec911ff28542/threejs/three.d.ts

r73 is too old... :(

**Comment by unphased** [comment]
This precise commit: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/8cb9ee3fdfe352cfef672bdfdb5f9c428f915e9f/threejs/three.d.ts

introduces the breakage

**Comment by kchodorow** [comment]
The issue is that there are certain TypeScript types that don't have names (e.g., there's an index type that seems to be triggering this bug).  Patching in the following did the trick for me:

```
diff --git a/src/parser.js b/src/parser.js                                                                                                                                                                  
index f4954df..aa754ac 100644                                                                                                                                                                               
--- a/src/parser.js                                                                                                                                                                                         
+++ b/src/parser.js                                                                                                                                                                                         
@@ -274,6 +275,9 @@ class Parser {                                                                                                                                                                          
       let type = {};                                                                                                                                                                                       

       node.type.members.forEach((member) => {                                                                                                                                                              
+        if (!member.name) {                                                                                                                                                                                
+          return;                                                                                                                                                                                          
+        }                                                                                                                                                                                                  
         type[member.name.text] = {};                                                                                                                                                                       
         this.appendType_(type[member.name.text], member);                                                                                                                                                  
       });
```

**Comment by unphased** [comment]
Brilliant... thank you

**Comment by kchodorow** [comment]
And here's the generated (and slightly massaged to remove a few bugs and things closure didn't understand, like `THREE.{}` and `@param {function(x:number)}`): https://github.com/kchodorow/fabricate-diem/blob/master/webapp/static/js/extern.js.

**Comment by unphased** [comment]
@kchodorow That works perfectly. To summarize, for my own reference, it seems like what you had to do was: 
1. patch `tsd2cce` with the patch you've provided :+1:
2. remove some `var` statements that got littered around. I count 13 of these. All but two of these needed to be removed, so something in `tsd2cce` is failing at this. 
3. remove `'use strict';`
4. bunch of unclear changes like replacing `THREE.{}` with `Object` and various `@param {function(x:number)}` stuff

I found that when I diff your `extern.js` with the one I was able to generate using your patch that there are a few more this that are different, such as `function` vs `Function` and two things that look like this `@return {Array<THREE.Vector2[]>}` where the `[]` part is removed... 

Suffice it to say this appears to be a very fragile situation and I hope that `tsd2cce` can be updated to work a bit better...

Meanwhile even though I got everything to run, my Three.js .obj loaded models don't get their textures loaded properly when my code is mangled with closure compiler using this method. 

Funny enough everything works perfectly with Uglifyjs2 without any need for defining externs and it produces a minified file that is only a few percent larger, so I'll personally be ditching closure and the JVM...

**Comment by jart** [comment]
Wow these are a lot of awesome discoveries. tsd2cce looks pretty good. Do you know if it's any better or worse than https://github.com/angular/tsickle which does the same thing?

This is something I've thought about a bit. I'm not really into TypeScript. But the TypeScript community has built a very expansive collection of high quality `.d.ts` files, whereas the same could not be said about `@externs` files. So backporting typescript externs to javascript and making them available in this project seems like it might benefit people.
